openapi: 3.0.1
info:
  title: test
  version: v6.19
paths:
  /path1:
    post:
      requestBody:
        content:
          application/json: {}
      responses:
        '200':
          description: Test
          content:
            application/json:
              schema:
                type: object
                properties:
                  brandId:
                    type: string
                    nullable: true