name: Storybook CD Workflow

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  call-storybook-cd-workflow:
    if: github.event_name == 'push' || github.event.ref_type == 'branch'
    uses: netcracker/qubership-apihub-ci/.github/workflows/storybook-cd.yaml@feature/ci-frontend-stability
